# Generated by Django 5.1.6 on 2025-03-11 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asosiy', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usertasdiqlash',
            old_name='code',
            new_name='kod',
        ),
    ]
