# Generated by Django 5.1.6 on 2025-04-02 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asosiy', '0002_rename_code_usertasdiqlash_kod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='royxat_bosqichi',
            field=models.CharField(choices=[('yangi', 'yangi'), ('kodni_tasdiqlash', 'kodni_tasdiqlash'), ('tasdiqlandi', 'tasdiqlandi'), ('rasm', 'rasm')], default='yangi', max_length=31),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_roli',
            field=models.CharField(choices=[('oddiy', 'oddiy'), ('manager', 'manager'), ('admin', 'admin')], default='oddiy', max_length=31),
        ),
    ]
